### ISSUE TITLE
Link BEDbase with pephub: use PEPhub for auto metadata update 

### ISSUE THREAD

**Issue by xuebingjie1990** [databio/bedbase#20]
use pephub to provide metadata for bedhost
use pephub to store BED set PEPs instead store the tar archive file on S3.  

https://github.com/pepkit/pephub/issues/21

**Comment by nsheff** [comment]
I think this is the same issue re-raised here: 

https://github.com/databio/bedbase/issues/56

I believe this is now basically working.
