### ISSUE TITLE
Bedbuncher/Bedhost-ui: How to organize/show BED sets with different ref genome on BEDbase.org 

### ISSUE THREAD

**Issue by xuebingjie1990** [databio/bedbase#23]
`bedbuncher` can create BED sets with BED files of different genome assembly. 

Things need to decide:
1) should we allow BED sets of multiple genomes
2) if so, how should we organize and display the BED sets stats with BED files of one genome assembly VS BED sets with multiple genomes assembly?

**Comment by khoroshevskyi** [comment]
We have new ui, and we will have new features there, closing this issue
