### ISSUE TITLE
Bedboss: testing with bedboss

### ISSUE THREAD

**Issue by xuebingjie1990** [databio/bedbase#24]
I tested `bedboss` with the tutorial files. It works without any error but there are some problems and questions I have @Khoroshevskyi : 
- [x] Need to fix: the 'median_tss_dist' column is empty
- [x] Need to fix: 'other' columns are not reported in the database (columns are empty) -- this is b/c the we are no longer calling the `looper` `pre-submit` function to generate the sample yaml file, where the `bedstat` read from for the `other` column
- [x] filter out local path in the sample yaml
- [x] the 'bed_files' and 'bigbed_files' are now renamed to 'files_bed' and 'files_bigbed'. is there a reason? if not, can we keep the way it is? other wise there are lots of other places need to change (ex s2 bucket, and all the existing bedfiles on bedbase ).
- [x]  the 'bed_files' and 'bigbed_files' are now inside the output dir. is that intentional? 
- [x]  all the bed files and bigbed files are now named by the {sample_name} instead of their original name. is that also intentional?

10/20 update:
- [x] I don't think we want `standard_genome_name()` function to limited the input to hg38, hg19, and mm10
- [x] About the `get_osm_path()` function: the R script has tryCatch to handle missing files needed for GD plots. we don't want to kill the pipeline at the beginning  because file required for one GD plot is missing

1/26 update:
- [x] do we want to add bedbuncher and bedembed as part of bedboss? @Khoroshevskyi

**Comment by xuebingjie1990** [comment]
@khoroshevskyi  can we close this issue?

**Comment by khoroshevskyi** [comment]
It is old issue, and it was solved for previous bedboss version
