### ISSUE TITLE
Streamline retrieving pephub metadata of bed records

### ISSUE THREAD

**Issue by nsheff** [databio/bedbase#56]
how can we connect a record identifier on bedbase to the metadata on pephub?

say I have this record: https://bedbase.org/bed/421d2128e183424fcc6a74269bae7934

I want the metadata, from pephub. how do I get it?

This needs to be really easy to do, and straightforward. We should document this.

And maybe we should rethink the current `/metadata` endpoint -- right now it's returning statistics, results that are reported by bedboss. But a user may naturally think of `/metadata` as the information that would be in pephub about the bed file.

Or maybe the combination? Basically, we need a streamline this so that a user can hit some endpoint and get the pephub metadata for a bed file.

@khoroshevskyi -- would like your ideas on how to tackle this.

**Comment by khoroshevskyi** [comment]
On the backend side, within bedsets, there is a link to PEPhub. Unfortunately, this link is not available for samples (bedfiles). Bedfiles represent samples, while bedsets represent projects. In this context, I am unsure how to connect bedfiles to PEPhub samples.
![image](https://github.com/databio/bedbase/assets/41573628/2cfdbebe-a362-4028-9450-4055478ee977)

**Comment by nsheff** [comment]
Can you update as to status of this issue? maybe document how to use this now? I think you can now access the metadata from pephub via bedbase. It would nice to write a blurb about this in docs somewhere.

**Comment by khoroshevskyi** [comment]
I am changing it quickly. I will have updates on this next week

**Comment by khoroshevskyi** [comment]
This issue was solved in v0.4.0
