### ISSUE TITLE
BEDbase documentation updates

### ISSUE THREAD

**Issue by nsheff** [databio/bedbase#63]
This issue is to track documentation improvements for the 2024-04 target release of BEDbase.

### Documentation updates:
- [x] Clean up actual docs
- [x] Update docs links following example of pephub.databio.org.
	- [x] Replace About link with link to https://docs.bedbase.org/ 
	- [x] Integrate About page documentation to main docs site
	- [x] Clean up the docs there (that About page was incomplete in the first place)
- [x] Write actual documentation at https://docs.bedbase.org/

**Comment by khoroshevskyi** [comment]
This issue is fixed, and will be gradually upgraded
