### ISSUE TITLE
Universes in the database

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bedbase#69]
What information should be stored in the database about universes?

Please add a comments with info what information should be stored about universes in the database.

**Comment by nsheff** [comment]
some things that come to mind immediately: source, and/or method of construction, maybe a link to a remote location if it was provided by an external provider, or publication? a description, maybe?

**Comment by khoroshevskyi** [comment]
This issue was solved in bbconf 0.6.0 and bedhost 0.5.0
