### ISSUE TITLE
2024-05 BEDbase sprint

### ISSUE THREAD

**Issue by nsheff** [databio/bedbase#73]
## Current deployment: 

- bedhost 0.4.1
- bbconf 0.5.1

## Component release targets for this BEDbase release on May 31:

- [x] bbconf v0.6.0: <https://github.com/databio/bbconf/milestone/1>
- [x] bedhost v0.5.0 <https://github.com/databio/bedhost/milestone/1>
- [x] bedboss v0.3.0: <https://github.com/databio/bedboss/milestone/6> ?

Additional issues for this release: 

- [x] Add more data to bedbase: https://github.com/databio/bedbase/issues/67
- [x] https://github.com/databio/geniml_dev/issues/156
- [x] https://github.com/databio/bedbase/issues/37

**Comment by khoroshevskyi** [comment]
As this is old sprint, And almost everything was solved, closing this issue
