### ISSUE TITLE
Following BEDbase releases

### ISSUE THREAD

**Issue by jwokaty** [databio/bedbase#83]
I noticed bedbase updated to 0.6.0, but the change log hasn't been updated. Is there something I can "watch" to make sure bedbaser follows the releases?

**Comment by nsheff** [comment]
probably the package to watch would be https://github.com/databio/bedhost -- because that's where the API is defined. You could subscribe to that repo, maybe?

**Comment by nsheff** [comment]
Also @khoroshevskyi make sure you update the changelog when you release updates. I know it's a bit harder since the docs are hosted in a different repo, but it's still important. looks like we're a few versions behind: https://docs.bedbase.org/bedhost/changelog/

**Comment by khoroshevskyi** [comment]
I have just updated changelog.

In new version of bedbase main changes are:

- Updated bed metadata endpoint: added annotation to metadata return model, with standard schema
- Updated metadata in search endpoints.
- Added embed endpoint. [#136](https://github.com/databio/bedhost/issues/136)
